[build-system]
requires = ["setuptools-cpp-cuda", "flit_core >=3.2,<4", "wheel", "cython"]
build-backend = "flit_core.buildapi"

[project]
name = "my-cpp-package"
dependencies = ["numpy"]
dynamic = ["version", "description"]
